{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "unity-collab.fullname" . }}
  labels:
    {{- include "unity-collab.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ include "unity-collab.fullname" $ }}-{{ .service }}
            port:
              number: {{ index $.Values (printf "%sService" .service) "service" "port" | default 80 }}
      {{- end }}
  {{- end }}
{{- end }}
